### ISSUE TITLE
FR: auto-localization

### ISSUE THREAD

**Issue by el-schneider** [spatie/statamic-algolia-places#1]
Hey, I just installed your addon and it seems to work really well! Thanks a lot for your work!

I was wondering if it would be possible to update the fetched information based on various site locales.
I for example am using a website with two locales and while Algolia Places can provide localized location data the addon lets me only choose a default for all sites.

I don't know if this is possible, however such a feature would be greatly appreciated.

**Comment by riasvdv** [comment]
I've added this for 1.0.2, if you leave the language empty in the field config, it should use the selected site's locale instead. Let me know if it works for your case!

**Comment by el-schneider** [comment]
Cool! I'll give it a try asap
