### ISSUE TITLE
Cacheable PLACES_API_KEY en PLACES_APP_ID

### ISSUE THREAD

**Issue by GertTimmerman** [spatie/statamic-algolia-places#2]
The PLACES_APP_ID and PLACES_API_KEY comes directly from the .env, when I run the command `php artisan optimize` then the fieldtype does not work anymore because the KEY and ID are not cached. Is it possible to make a config file that can be cached?

**Comment by riasvdv** [comment]
We definitely could, but I'm hesitant of doing further development on this addon, as Algolia is sunsetting places https://www.algolia.com/blog/product/sunseting-our-places-feature/

Do you need this for a site that's already running? If it's for one still in development I'd search for a different solution
